### ISSUE TITLE
Create a draft of standardized format for contribute.md

### ISSUE THREAD

**Issue by BenGitsCode** [BenGitsCode/today-i-learned#1]
standards make everything better. I'd like the format to be pretty open, but a good starting place would be helpful.

**Comment by MicFin** [comment]
Something like this might be a good starting point to take some snippets from and use as standards. 
https://github.com/RichardLitt/standard-readme/blob/master/spec.md#sections

**Comment by BenGitsCode** [comment]
@MicFin I have a draft using pieces of Richard Litt's standard-readme (used it for the readme as well) as well as some snippets from the massive and awesome [CONTRIBUTING.md for Atom](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)

I'll push what I have so far, and polish it up soon.

**Comment by BenGitsCode** [comment]
Rough draft here https://github.com/BenGitsCode/today-i-learned/blob/master/CONTRIBUTE.md It's usable now but still needs work.
